In [37]:
import pandas as pd
import pickle
import numpy as np
from tensorflow import keras

In [4]:
mit_test = pd.read_csv("../data/mitbih_test.csv", header = None)

In [32]:
mit_test_X = mit_test.iloc[:,:-1]
mit_test_y = mit_test.iloc[:,-1]

In [10]:
loaded_model = pickle.load(open("../models/LR_2.h5", 'rb'))

In [30]:
loaded_model.predict(mit_test_X)

array([1., 0., 0., ..., 2., 4., 4.])

In [14]:
mit_test_X.iloc[10,:]

0      0.997429
1      0.861183
2      0.365039
3      0.071979
4      0.082262
         ...   
182    0.000000
183    0.000000
184    0.000000
185    0.000000
186    0.000000
Name: 10, Length: 187, dtype: float64

In [28]:
np.array([10]).reshape(-1,1)

array([[10]])

In [33]:
mit_test_y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
21887    4.0
21888    4.0
21889    4.0
21890    4.0
21891    4.0
Name: 187, Length: 21892, dtype: float64

In [35]:
len(loaded_model.predict(mit_test_X))

21892

In [40]:
CNN_1 = keras.models.load_model("../models/CNN_1.h5")

In [42]:
CNN_1.predict(mit_test_X).argmax(1)

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [43]:
users_bdd = {
  "alice": "wonderland",
  "bob": "builder",
  "clementine": "mandarine"
}

In [44]:
users_bdd.get("alice")

'wonderland'